INSERT INTO CAR(ID, NOMBRE, MARCA, MODELO) VALUES (100, 'Tsuru', 'Nissan', '2012');
INSERT INTO CAR(ID, NOMBRE, MARCA, MODELO) VALUES (20, 'Spark', 'Chevrolet', '2020');
INSERT INTO CAR(ID, NOMBRE, MARCA, MODELO) VALUES (33, 'Focus', 'Ford', '2024');
INSERT INTO CAR(ID, NOMBRE, MARCA, MODELO) VALUES (41, 'MazdaSpeed 3', 'Mazda', '2013');